-- 1번 문제 -- 비트연산자 &
SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE NOT(GENOTYPE & 2) AND (GENOTYPE & 1 OR GENOTYPE & 4)

-- 2번 문제 -- 
SELECT ID, LENGTH
FROM FISH_INFO
ORDER BY LENGTH DESC, ID ASC
LIMIT 10;

-- 3번 문제 --
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE YEAR(TIME) = '2021';

-- 4번 문제 -- 
SELECT CONCAT(MAX(LENGTH),'cm') AS MAX_LENGTH
FROM FISH_INFO
ORDER BY LENGTH DESC
LIMIT 1;

-- 5번 문제 -- 
SELECT ROUND(AVG(IFNULL(LENGTH,10)),2) AS AVERAGE_LENGTH
FROM FISH_INFO;

-- 6번 문제 -- 
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE LENGTH < 10 or LENGTH IS NULL;

-- 7번 문제 -- 
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPER_INFOS
WHERE 'Python' IN (SKILL_1,SKILL_2,SKILL_3)
ORDER BY ID;

-- 8번 문제 --
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, date_format(R.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD AS B JOIN USED_GOODS_REPLY AS R 
ON B.BOARD_ID = R.BOARD_ID
WHERE YEAR(B.CREATED_DATE) = 2022 AND MONTH(B.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE, B.TITLE

-- 9번 문제 -- # LIKE % % 연산자
SELECT CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%네비게이션%'
ORDER BY 1 DESC;

-- 10번 문제 --  IN (복수 값)
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ('Lucy','Ella','Pickle','Rogan','Sabrina','Mitty')
ORDER BY 1;

-- 11번 문제 -- 
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS 
WHERE NAME LIKE '%EL%' AND ANIMAL_TYPE = 'Dog'
ORDER BY 2;

-- 12번 문제 -- 
SELECT ANIMAL_ID, NAME,
        CASE WHEN SEX_UPON_INTAKE LIKE '%NEUTERED%' or SEX_UPON_INTAKE LIKE '%SPAYED%' THEN 'O'
        ELSE 'X'
        END AS '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

-- 13번 문제 -- ORDER BY에 계산식을 넣어도 됨
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS AS O JOIN ANIMAL_INS AS I
ON O.ANIMAL_ID = I.ANIMAL_ID
ORDER BY O.DATETIME - I.DATETIME DESC
LIMIT 2;

-- 14번 문제 --  GROUP BY 별 
SELECT LEFT(PRODUCT_CODE,2) AS CATEGORY, COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY;

-- 15번 문제 --  DATEDIFF(DATE1, DATE2)
SELECT HISTORY_ID, CAR_ID, date_format(START_DATE,'%Y-%m-%d') AS START_DATE,date_format(END_DATE,'%Y-%m-%d') AS END_DATE,
CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '장기 대여'
ELSE '단기 대여'
END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) = 9
ORDER BY HISTORY_ID DESC;

-- 16번 문제 -- 
SELECT  ROUND(AVG(DAILY_FEE), 0) AS AVERAGE_FEE
FROM  CAR_RENTAL_COMPANY_CAR
WHERE  CAR_TYPE = 'SUV';

-- 17번 문제 --
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(USER_ID) >=2
ORDER BY USER_ID,PRODUCT_ID DESC;

-- 18번 문제 -- 
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
from ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m')='2022-03'

UNION

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') SALES_DATE,PRODUCT_ID, NULL 'USER_NAME',SALES_AMOUNT
from OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m')='2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

-- 19번 문제 -- 
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION LIKE '%SICK%'
ORDER BY 1;

-- 20번 문제 -- 
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION NOT LIKE '%AGED%'
ORDER BY 1;

-- 21번 문제 --
SELECT DISTINCT ANIMAL_ID, NAME
FROM ANIMAL_INS
GROUP BY 1,2
ORDER BY 1;

-- 22번 문제 -- 
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY 2, 3 DESC;

-- 23번 문제 -- 
SELECT NAME 
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1;

-- 24번 문제 --
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE AGE >=20 AND AGE <=29 AND YEAR(JOINED) = 2021

-- 25번 문제 --
SELECT BOOK_ID,DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK 
WHERE CATEGORY LIKE '인문' AND YEAR(PUBLISHED_DATE) = 2021
ORDER BY PUBLISHED_DATE;

-- 26번 문제 --
SELECT F.FLAVOR
FROM FIRST_HALF AS F JOIN ICECREAM_INFO AS I
ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER > 3000 AND I.INGREDIENT_TYPE LIKE '%FRUIT_BASED%'
ORDER BY F.TOTAL_ORDER DESC;

-- 27번 문제 -- 
SELECT FLAVOR
FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC;

-- 28번 문제 -- 
SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, '%Y-%m-%d') AS HIRE_YMD
FROM DOCTOR 
WHERE MCDP_CD LIKE '%CS%' OR MCDP_CD LIKE '%GS'
ORDER BY 4 DESC, 1;

-- 29번 문제 -- IS NULL 명심하기
SELECT PT_NAME, PT_NO, GEND_CD, AGE ,CASE WHEN TLNO IS NULL THEN 'NONE'
ELSE TLNO
END AS TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD LIKE '%W%'
ORDER BY AGE DESC, PT_NAME ASC;

-- 30번 문제 -- 
SELECT MAX(PRICE) AS MAX_PRICE
FROM PRODUCT
LIMIT 1;

-- 31번 문제 -- 
SELECT COUNT(USER_ID) AS USERS
FROM USER_INFO
WHERE AGE IS NULL;

-- 32번 문제 -- 
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, CASE WHEN FREEZER_YN IS NULL THEN 'N'
ELSE FREEZER_YN
END AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '%경기도%'
ORDER BY 1;

-- 33번 문제 -- 
SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
FROM FOOD_FACTORY
WHERE ADDRESS LIKE '%강원도%'
ORDER BY 1;

-- 34번 문제 -- 
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY 1;

-- 35번 문제 --
SELECT ANIMAL_ID
FROM ANIMAL_INS 
WHERE NAME IS NULL
ORDER BY 1;

-- 36번 문제 -- 
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC;

-- 37번 문제 --
SELECT * 
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;



